import './search-room.scss'
import '../../modules/header/header'
import '../../modules/dropdown/dropdown'
import '../../modules/filter-date-dropdown/filter-date-dropdown'
import '../../modules/range-slider/range-slider'
import '../../modules/expandable-checkbox-list/expandable-checkbox-list'
import '../../modules/room-card/room-card'
import '../../modules/footer/footer'